"""Central logging configuration.

Goals (in priority order):
  1. **Structured** — every record is a JSON line (one JSON object per
     log entry, newline-delimited). Greppable, parseable, ships well
     to anything that ingests JSONL (Loki, Elasticsearch, just `jq`).
  2. **Rotated** — bounded disk use (10 MB × 5 backups = 50 MB cap)
     so logs can never fill the disk. Under systemd, journald owns
     rotation so the file handler is skipped.
  3. **Redact secrets** — a filter strips obvious api_key=/token=/
     password=/Bearer-style values BEFORE the record hits any
     handler. Defense in depth; the codebase shouldn't be logging
     those anyway.
  4. **Persist errors** — WARNING+ records also land in a SQLite
     `error_log` table so Settings → Health can show a "what's been
     breaking" list without grepping /tmp or journald.

Call `setup_logging()` exactly once on app import — `backend/main.py`
does this before any router is registered so every subsequent
`getLogger(...)` call inherits the handlers.
"""

from __future__ import annotations

import contextvars
import json
import logging
import logging.handlers
import os
import re
import sys
import traceback as _traceback
from pathlib import Path
from typing import Any, Optional


# ─── Correlation ID ──────────────────────────────────────────────────
# Per-request id generated by middleware in main.py. Filter below
# stamps it onto every LogRecord emitted within the request's task,
# so a tester can grep `corr=<id>` and see every log line tied to one
# user action — across skill calls, LLM calls, upstream calls, etc.
# Outside an HTTP request (background tasks, startup) the value stays
# None and the field is simply omitted from the JSON record.

correlation_id: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "yorik_correlation_id", default=None,
)


class CorrelationFilter(logging.Filter):
    """Stamps the active correlation id onto every record as `corr`."""

    def filter(self, record: logging.LogRecord) -> bool:
        cid = correlation_id.get()
        if cid:
            record.corr = cid
        return True

# ─── Paths + tunables ────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOG_DIR = Path(os.getenv("YORIK_LOG_DIR", str(PROJECT_ROOT / "data" / "logs")))
LOG_FILE = LOG_DIR / "yorik.log"
LOG_LEVEL = os.getenv("YORIK_LOG_LEVEL", "INFO").upper()
MAX_BYTES = int(os.getenv("YORIK_LOG_MAX_MB", "10")) * 1024 * 1024
BACKUP_COUNT = int(os.getenv("YORIK_LOG_BACKUPS", "5"))


# ─── Secrets filter ──────────────────────────────────────────────────

# Patterns we redact in log messages. Each regex's group(0) is replaced
# with `<key>=<REDACTED>` so the structure of the message is preserved
# (greppable by key, just the value is gone).
_SECRET_PATTERNS = [
    # api_key=abc123, api_key: "abc123", api_key="abc123"
    (re.compile(r'(?i)(api[_-]?key|secret|password|passphrase|token|x-api-key|authorization)'
                r'\s*[:=]\s*"?([A-Za-z0-9._\-+/=]{8,})"?'),
     r'\1=<REDACTED>'),
    # Bearer abc123
    (re.compile(r'(?i)(bearer)\s+([A-Za-z0-9._\-+/=]{8,})'),
     r'\1 <REDACTED>'),
    # bcrypt hashes — never useful in logs, leaks the hash format
    (re.compile(r'\$2[aby]?\$\d{1,2}\$[./A-Za-z0-9]{53}'),
     '<BCRYPT-HASH-REDACTED>'),
]


class SecretsFilter(logging.Filter):
    """Strip recognisable secrets from log records BEFORE any handler
    formats them. Applies to both the formatted message and any string
    args. Non-string args (dicts, lists) are left alone — those rarely
    leak secrets, and recursing through them would slow the log path."""

    def filter(self, record: logging.LogRecord) -> bool:
        if isinstance(record.msg, str):
            record.msg = self._scrub(record.msg)
        if record.args:
            if isinstance(record.args, dict):
                record.args = {k: self._scrub(v) if isinstance(v, str) else v
                               for k, v in record.args.items()}
            elif isinstance(record.args, tuple):
                record.args = tuple(self._scrub(a) if isinstance(a, str) else a
                                    for a in record.args)
        return True

    @staticmethod
    def _scrub(s: str) -> str:
        out = s
        for pat, repl in _SECRET_PATTERNS:
            out = pat.sub(repl, out)
        return out


# ─── JSON formatter ──────────────────────────────────────────────────

# Standard LogRecord attributes we DON'T want in the JSON output (the
# formatter exposes message/levelname/etc. as top-level fields; these
# are framework chrome that just clutters every line).
_STDLIB_RESERVED = {
    "name", "msg", "args", "levelname", "levelno", "pathname", "filename",
    "module", "exc_info", "exc_text", "stack_info", "lineno", "funcName",
    "created", "msecs", "relativeCreated", "thread", "threadName",
    "processName", "process", "asctime", "taskName",
}


class JsonFormatter(logging.Formatter):
    """One JSON object per log record, newline-delimited.

    Output shape (minimum):
      {"ts": "2026-05-22T10:30:00.123Z", "level": "INFO",
       "logger": "yorik.startup", "msg": "started"}

    Anything passed to `logger.X("…", extra={...})` lands as
    top-level fields on the record. Exception info is rendered as
    a "traceback" string field on records with exc_info.
    """

    def format(self, record: logging.LogRecord) -> str:
        # Apply args substitution (e.g. "%s" replacement) the standard way.
        try:
            message = record.getMessage()
        except Exception:
            message = str(record.msg)

        out: dict[str, Any] = {
            "ts":     self.formatTime(record, "%Y-%m-%dT%H:%M:%S") +
                      f".{int(record.msecs):03d}Z",
            "level":  record.levelname,
            "logger": record.name,
            "msg":    message,
        }
        if record.exc_info:
            out["traceback"] = "".join(_traceback.format_exception(*record.exc_info))

        # Surface any `extra={...}` fields the caller passed.
        for k, v in record.__dict__.items():
            if k in _STDLIB_RESERVED or k.startswith("_"):
                continue
            if k in out:  # don't let extras shadow built-ins
                continue
            try:
                json.dumps(v)
                out[k] = v
            except (TypeError, ValueError):
                out[k] = repr(v)

        return json.dumps(out, ensure_ascii=False, default=str)


# ─── Setup ───────────────────────────────────────────────────────────

_initialized = False


def setup_logging() -> None:
    """Install handlers + filter on the root logger. Idempotent — safe
    to call multiple times (subsequent calls are no-ops)."""
    global _initialized
    if _initialized:
        return
    _initialized = True

    root = logging.getLogger()
    root.setLevel(LOG_LEVEL)

    # Strip whatever handlers uvicorn installed so our JSON output is
    # the canonical sink. We re-attach a stderr handler below.
    for h in list(root.handlers):
        root.removeHandler(h)

    fmt = JsonFormatter()
    secrets = SecretsFilter()
    corr = CorrelationFilter()

    # Stderr handler always present — humans reading `journalctl -u yorik`
    # or `tail -f /tmp/homeos-api.log` need to see something.
    stderr = logging.StreamHandler(sys.stderr)
    stderr.setFormatter(fmt)
    stderr.addFilter(secrets)
    stderr.addFilter(corr)
    root.addHandler(stderr)

    # File handler only when NOT running under systemd. Under systemd,
    # journald handles rotation + retention; doubling up creates two
    # truths and burns disk.
    if not os.environ.get("INVOCATION_ID"):
        try:
            LOG_DIR.mkdir(parents=True, exist_ok=True)
            file_handler = logging.handlers.RotatingFileHandler(
                str(LOG_FILE),
                maxBytes=MAX_BYTES,
                backupCount=BACKUP_COUNT,
                encoding="utf-8",
            )
            file_handler.setFormatter(fmt)
            file_handler.addFilter(secrets)
            file_handler.addFilter(corr)
            root.addHandler(file_handler)
        except OSError as exc:
            # Don't crash startup just because we can't write a log
            # file (read-only FS, perm issue). Stderr still works.
            root.warning("logging_setup: file handler disabled (%s)", exc)

    # SQLite error_log handler — only WARNING+, fire-and-forget so a
    # DB blip doesn't propagate into the log path.
    try:
        from . import error_log as _error_log
        sqlite_handler = _error_log.SqliteErrorHandler()
        sqlite_handler.setLevel(logging.WARNING)
        sqlite_handler.addFilter(secrets)
        sqlite_handler.addFilter(corr)
        root.addHandler(sqlite_handler)
    except Exception as exc:
        root.warning("logging_setup: SQLite error_log handler disabled (%s)", exc)

    # Quiet the noisier libraries — uvicorn's access logs in particular
    # are useful but at INFO level they drown signal.
    logging.getLogger("uvicorn.access").setLevel("WARNING")
    logging.getLogger("watchfiles").setLevel("WARNING")

    root.info("logging_setup: initialised (level=%s, file=%s)",
              LOG_LEVEL,
              "journald" if os.environ.get("INVOCATION_ID") else str(LOG_FILE))
