-- Yorik Phase D bootstrap — autogenerated from SQLite end-state schema.
-- See scripts/dump_sqlite_to_postgres.py for the translator.
-- Re-running is safe (every DDL is IF NOT EXISTS-equivalent).

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS docs;

-- =================== family.db tables ===================

CREATE TABLE IF NOT EXISTS events (
    id            BIGSERIAL PRIMARY KEY,
    title         TEXT NOT NULL,
    starts_at     TEXT NOT NULL,
    ends_at       TEXT,
    all_day       INTEGER NOT NULL DEFAULT 0,
    color         TEXT,
    person        TEXT,
    notes         TEXT,
    recurring     TEXT,
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, calendar_id     INTEGER, owner_user_id   INTEGER, visibility      TEXT NOT NULL DEFAULT 'default', location TEXT, location_lat DOUBLE PRECISION, location_lon DOUBLE PRECISION, travel_time_s INTEGER, travel_distance_m INTEGER, travel_provider TEXT, travel_computed_at TEXT, category TEXT, space_id INTEGER);

CREATE TABLE IF NOT EXISTS tasks (
    id            BIGSERIAL PRIMARY KEY,
    title         TEXT NOT NULL,
    due_date      TEXT,
    done          INTEGER NOT NULL DEFAULT 0,
    person        TEXT,
    category      TEXT,
    notes         TEXT,
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, priority INTEGER NOT NULL DEFAULT 1, estimated_minutes INTEGER, created_by_user_id INTEGER, parent_task_id INTEGER, recurrence_rule TEXT, space_id INTEGER);

CREATE TABLE IF NOT EXISTS task_categories (
    id         BIGSERIAL PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    color      TEXT NOT NULL DEFAULT '#818cf8',
    position   INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS bills (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    amount        DOUBLE PRECISION NOT NULL,
    currency      TEXT NOT NULL DEFAULT 'EUR',
    due_date      TEXT NOT NULL,
    recurring     TEXT,
    paid          INTEGER NOT NULL DEFAULT 0,
    notes         TEXT,
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, email_message_id INTEGER, document_id INTEGER, space_id INTEGER);

CREATE TABLE IF NOT EXISTS user_profiles (
    id              BIGSERIAL PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    email           TEXT,
    role            TEXT NOT NULL,
    voice_id        TEXT,
    voice_embedding TEXT,                            -- JSON list[float] (192-dim ECAPA)
    language        TEXT NOT NULL DEFAULT 'en',      -- TTS voice + LLM reply language
    preferred_layout TEXT NOT NULL DEFAULT 'google',
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, password_hash TEXT, disabled INTEGER NOT NULL DEFAULT 0, password_set_at TEXT, last_login_at TEXT, paperless_user_id INTEGER, paperless_token TEXT, immich_user_id TEXT, immich_api_key TEXT, country TEXT, address_street TEXT, address_postcode TEXT, address_city TEXT, phone TEXT, business_name TEXT, tax_id TEXT, iban TEXT, onboarded_at TEXT, confirm_mutations INTEGER NOT NULL DEFAULT 1, voice_ack_enabled INTEGER NOT NULL DEFAULT 1, dev_mode INTEGER NOT NULL DEFAULT 0
        CHECK (dev_mode IN (0, 1)), default_doc_visibility TEXT
    NOT NULL DEFAULT 'private', first_name TEXT, last_name  TEXT, signature_data_url TEXT, pin_hash TEXT, pin_set_at TEXT, kiosk_agenda_consent INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS saved_queries (
    id              BIGSERIAL PRIMARY KEY,
    trigger_phrase  TEXT NOT NULL UNIQUE,
    sql_query       TEXT NOT NULL,
    view_command    TEXT,
    response_text   TEXT,
    use_count       INTEGER NOT NULL DEFAULT 0,
    last_used       TEXT
, workspace_id INTEGER);

CREATE TABLE IF NOT EXISTS conversations (
    id          TEXT PRIMARY KEY,
    user_role   TEXT NOT NULL,
    messages    TEXT NOT NULL DEFAULT '[]',
    created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, space_id INTEGER);

CREATE TABLE IF NOT EXISTS connector_credentials (
    connector_name  TEXT PRIMARY KEY,
    payload         BYTEA NOT NULL,
    updated_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, workspace_id INTEGER);

CREATE TABLE IF NOT EXISTS connector_grants (
    id              BIGSERIAL PRIMARY KEY,
    layout_id       TEXT NOT NULL,
    connector_name  TEXT NOT NULL,
    granted_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    granted_by_role TEXT NOT NULL,
    revoked_at      TEXT, workspace_id INTEGER,
    UNIQUE (layout_id, connector_name)
);

CREATE TABLE IF NOT EXISTS app_grants (
    id              BIGSERIAL PRIMARY KEY,
    app_id          TEXT NOT NULL,
    resource_type   TEXT NOT NULL,    -- 'table' | 'connector'
    resource_db     TEXT,             -- 'family' | 'documents' | NULL for connector grants
    resource_name   TEXT NOT NULL,    -- table name or connector id
    access          TEXT NOT NULL,    -- 'read' | 'write' | 'read+write'
    granted_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    granted_by_role TEXT NOT NULL,
    revoked_at      TEXT,
    UNIQUE (app_id, resource_type, resource_db, resource_name)
);

CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS sessions (
    id              TEXT PRIMARY KEY,           -- urlsafe random 32-byte token
    user_id         INTEGER NOT NULL,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    expires_at      TEXT NOT NULL,              -- datetime('now', '+30 days') by default
    last_seen_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    user_agent      TEXT,                       -- first 200 chars of the UA for "your devices" UI
    ip_seen         TEXT, is_kiosk        INTEGER NOT NULL DEFAULT 0, kiosk_album_id  TEXT, device_label    TEXT, trusted_until   TEXT, kiosk_show_today_photos INTEGER NOT NULL DEFAULT 0, kiosk_block_phrases TEXT, kiosk_hotword_enabled INTEGER NOT NULL DEFAULT 0                       -- last IP that used this session

);

CREATE TABLE IF NOT EXISTS template_cache (
    id              BIGSERIAL PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    source_url      TEXT,
    body            TEXT NOT NULL,
    fields_json     TEXT,
    fetched_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS wa_chats (
    jid               TEXT PRIMARY KEY,         -- "4915123456789@s.whatsapp.net" or "...@g.us"
    name              TEXT,
    is_group          INTEGER NOT NULL DEFAULT 0,
    last_message_ts   INTEGER,
    last_message_text TEXT,
    unread_count      INTEGER NOT NULL DEFAULT 0,
    owner_user_id     INTEGER NOT NULL DEFAULT 1,
    pinned            INTEGER NOT NULL DEFAULT 0,
    archived          INTEGER NOT NULL DEFAULT 0,
    created_at        TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, space_id INTEGER);

CREATE TABLE IF NOT EXISTS wa_self_identity (
    owner_user_id  BIGSERIAL PRIMARY KEY,
    me_jid         TEXT,        -- e.g. "4915xxx:7@s.whatsapp.net" (with device suffix)
    pushname       TEXT,        -- e.g. "Tom"
    updated_at     INTEGER NOT NULL
, space_id INTEGER);

CREATE TABLE IF NOT EXISTS wa_drafts (
    id            BIGSERIAL PRIMARY KEY,
    chat_jid      TEXT NOT NULL,
    draft_text    TEXT NOT NULL,
    sources_json  TEXT,                         -- JSON list of {kind, ref, snippet}
    sent_msg_id   TEXT,                         -- set once user clicks send
    sent_text     TEXT,                         -- what was actually sent (may differ from draft_text)
    owner_user_id INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), status TEXT NOT NULL DEFAULT 'pending', variant_group_id TEXT, variant_label TEXT, discarded_at TEXT, discard_reason TEXT, trigger_msg_id TEXT, space_id INTEGER
);

CREATE TABLE IF NOT EXISTS email_accounts (
    id              BIGSERIAL PRIMARY KEY,
    owner_user_id   INTEGER NOT NULL,
    email           TEXT NOT NULL,
    display_name    TEXT,                      -- "Personal Gmail", "Work"
    -- Connection config. ssl=true → port 993/465 implicit TLS.
    -- starttls=true → port 143/587 STARTTLS. We support both.
    imap_host       TEXT NOT NULL,
    imap_port       INTEGER NOT NULL DEFAULT 993,
    imap_ssl        INTEGER NOT NULL DEFAULT 1,
    imap_username   TEXT NOT NULL,
    smtp_host       TEXT NOT NULL,
    smtp_port       INTEGER NOT NULL DEFAULT 465,
    smtp_ssl        INTEGER NOT NULL DEFAULT 1,
    smtp_starttls   INTEGER NOT NULL DEFAULT 0,
    smtp_username   TEXT NOT NULL,
    -- Credential store reference. The actual password lives encrypted
    -- in the credential_store table at key='email:<account_id>'.
    credential_key  TEXT,
    -- Sync controls.
    enabled         INTEGER NOT NULL DEFAULT 1,
    is_default      INTEGER NOT NULL DEFAULT 0,   -- which account /send defaults to
    last_sync_at    TEXT,
    last_error      TEXT,                          -- human-readable last failure
    last_error_at   TEXT,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), imap_starttls INTEGER NOT NULL DEFAULT 0, space_id INTEGER,
    UNIQUE (owner_user_id, email)
);

CREATE TABLE IF NOT EXISTS email_folders (
    id              BIGSERIAL PRIMARY KEY,
    account_id      INTEGER NOT NULL,
    name            TEXT NOT NULL,             -- raw IMAP folder name (e.g. "[Gmail]/All Mail")
    display_name    TEXT,                      -- prettified for UI
    flags           TEXT,                      -- JSON of \HasNoChildren / \Sent / \All / etc.
    uid_validity    INTEGER,
    uid_next        INTEGER,                   -- highest UID we've seen + 1
    message_count   INTEGER NOT NULL DEFAULT 0,
    unread_count    INTEGER NOT NULL DEFAULT 0,
    last_sync_at    TEXT, space_id INTEGER,
    UNIQUE (account_id, name)
);

CREATE TABLE IF NOT EXISTS email_messages (
    id              BIGSERIAL PRIMARY KEY,
    account_id      INTEGER NOT NULL,
    folder_id       INTEGER,
    uid             INTEGER NOT NULL,          -- IMAP UID within folder
    message_id      TEXT,                      -- RFC822 Message-ID — primary thread key
    in_reply_to     TEXT,                      -- threading
    references_ids  TEXT,                      -- JSON array of Message-IDs from References header
    thread_id       TEXT,                      -- derived; same for all messages in conversation
    from_email      TEXT,
    from_name       TEXT,
    to_addrs        TEXT,                      -- JSON list of {email, name}
    cc_addrs        TEXT,
    reply_to        TEXT,
    subject         TEXT,
    snippet         TEXT,
    body_text       TEXT,
    body_html       TEXT,
    date_sent       TEXT,
    date_received   TEXT,
    size_bytes      INTEGER,
    is_unread       INTEGER NOT NULL DEFAULT 1,
    is_starred      INTEGER NOT NULL DEFAULT 0,
    is_sent         INTEGER NOT NULL DEFAULT 0,
    is_draft        INTEGER NOT NULL DEFAULT 0,
    has_attachments INTEGER NOT NULL DEFAULT 0,
    category        TEXT,                      -- LLM-assigned: priority / reply_needed / news / promo
    owner_user_id   INTEGER NOT NULL,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), snoozed_until TEXT, list_unsubscribe       TEXT, list_unsubscribe_post  TEXT, space_id INTEGER,
    UNIQUE (account_id, folder_id, uid)
);

CREATE TABLE IF NOT EXISTS email_attachments (
    id              BIGSERIAL PRIMARY KEY,
    message_id      INTEGER NOT NULL,
    filename        TEXT,
    mimetype        TEXT,
    size_bytes      INTEGER,
    content_id      TEXT,                      -- for inline images referenced from HTML
    is_inline       INTEGER NOT NULL DEFAULT 0,
    local_path      TEXT,                      -- where we stashed the binary
    paperless_id    INTEGER,                   -- if auto-routed (future)
    immich_id       TEXT, space_id INTEGER                      -- if auto-routed (future)

);

CREATE TABLE IF NOT EXISTS email_drafts (
    id              BIGSERIAL PRIMARY KEY,
    message_id      INTEGER NOT NULL,            -- email_messages.id we're replying to
    thread_id       TEXT,
    draft_text      TEXT NOT NULL,
    variant_label   TEXT,                        -- brief / warm / detailed
    variant_group_id TEXT,                       -- shared across siblings
    status          TEXT NOT NULL DEFAULT 'pending',  -- pending / used / discarded
    sent_msg_id     INTEGER,                     -- the email_messages row created on send
    discard_reason  TEXT,                        -- manual_reply / regenerated / user_dismissed / sibling_used
    discarded_at    TEXT,
    sources_json    TEXT,
    owner_user_id   INTEGER NOT NULL,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), space_id INTEGER
);

CREATE TABLE IF NOT EXISTS backups (
    id            BIGSERIAL PRIMARY KEY,
    target_path   TEXT NOT NULL,
    filename      TEXT NOT NULL,        -- relative to target_path
    size_bytes    INTEGER,
    status        TEXT NOT NULL,        -- 'ok' | 'failed'
    error         TEXT,                 -- only when status='failed'
    duration_s    DOUBLE PRECISION,
    includes      TEXT,                 -- JSON array of what was bundled
    started_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    finished_at   TEXT
);

CREATE TABLE IF NOT EXISTS task_assignees (
    task_id    INTEGER NOT NULL,
    user_id    INTEGER NOT NULL,
    status     TEXT NOT NULL DEFAULT 'pending',  -- pending | accepted | declined | done
    assigned_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    decided_at  TEXT,
    PRIMARY KEY (task_id, user_id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id           BIGSERIAL PRIMARY KEY,
    user_id      INTEGER NOT NULL,            -- WHO to notify
    kind         TEXT NOT NULL,                -- 'task_assigned', 'task_status', ...
    title        TEXT NOT NULL,
    body         TEXT,                          -- short preview text
    payload_json TEXT,                          -- JSON for kind-specific extras (ids, deep links)
    navigate_to  TEXT,                          -- relative URL the bell click should open
    is_read      INTEGER NOT NULL DEFAULT 0,
    read_at      TEXT,
    created_at   TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), space_id INTEGER
);

CREATE TABLE IF NOT EXISTS document_series (
    id              BIGSERIAL PRIMARY KEY,
    kind            TEXT NOT NULL,             -- 'rechnung'|'angebot'|'gutschrift'|'mahnung'|'invoice'|'quote'|...
    name            TEXT NOT NULL,             -- human-readable: "Rechnungen 2026"
    scheme          TEXT NOT NULL,             -- format with {prefix}{year}{seq:N} placeholders
    prefix          TEXT NOT NULL DEFAULT '',  -- 'R-' or '' or 'KU-' (Kundennummer style)
    seq_padding     INTEGER NOT NULL DEFAULT 3, -- zero-pad the sequence: 3 → 001, 4 → 0001
    next_number     INTEGER NOT NULL DEFAULT 1, -- THE next sequence value to be allocated
    year_reset      INTEGER NOT NULL DEFAULT 1, -- reset sequence at new year (most German setups: yes)
    current_year    INTEGER,                    -- the year of the last allocation, for the reset check
    owner_user_id   INTEGER,                    -- per-user series; NULL = household-shared
    is_default      INTEGER NOT NULL DEFAULT 0, -- the auto-pick for templates that match this kind
    notes           TEXT,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), workspace_id INTEGER
);

CREATE TABLE IF NOT EXISTS document_series_allocations (
    id                  BIGSERIAL PRIMARY KEY,
    series_id           INTEGER NOT NULL,
    number              INTEGER NOT NULL,        -- the raw integer (without prefix/year padding)
    formatted           TEXT NOT NULL,           -- the resolved string actually printed on the doc
    year                INTEGER NOT NULL,        -- the year at consume-time (for the reset/audit)
    document_kind       TEXT,                    -- 'rechnung' etc — same as series.kind, denormed for fast lookup
    consumed_by_user_id INTEGER,
    paperless_doc_id    INTEGER,                 -- linked Paperless doc if Save-to-Paperless landed
    pdf_sha256          TEXT,                    -- the rendered PDF's hash — GoBD audit chain
    title               TEXT,                    -- what the user titled the document
    notes               TEXT,
    consumed_at         TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), workspace_id INTEGER,
    UNIQUE(series_id, year, number)
);

CREATE TABLE IF NOT EXISTS turn_feedback (
    id              BIGSERIAL PRIMARY KEY,
    conversation_id TEXT,
    message_idx     INTEGER,                       -- index within the conversation
    rating          INTEGER NOT NULL,              -- +1 thumbs up, -1 thumbs down
    note            TEXT,                          -- optional free text
    llm_model       TEXT,                          -- which model produced the turn
    user_id         INTEGER,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS skill_invocations (
    id              BIGSERIAL PRIMARY KEY,
    skill_id        TEXT NOT NULL,
    llm_model       TEXT,
    success         INTEGER NOT NULL,              -- 1 success / 0 failure
    error           TEXT,                          -- short failure reason if !success
    latency_ms      INTEGER,
    conversation_id TEXT,
    user_id         INTEGER,
    args_json       TEXT,                          -- JSON-encoded skill args, ~1KB cap
    result_summary  TEXT,                          -- str(result), ~1KB cap
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS template_ratings (
    id          BIGSERIAL PRIMARY KEY,
    template_id TEXT NOT NULL,
    rating      INTEGER NOT NULL,                  -- +1 / -1
    llm_model   TEXT,                              -- which model auto-filled / generated it
    note        TEXT,
    user_id     INTEGER,
    created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS compose_drafts (
                id           BIGSERIAL PRIMARY KEY,
                user_id      INTEGER NOT NULL,
                kind         TEXT NOT NULL DEFAULT 'letter',
                template_id  TEXT,
                recipient    TEXT,
                subject      TEXT,
                body_html    TEXT NOT NULL DEFAULT '',
                args_json    TEXT NOT NULL DEFAULT '{}',
                created_at   TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
                updated_at   TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
            );

CREATE TABLE IF NOT EXISTS error_log (
    id           BIGSERIAL PRIMARY KEY,
    ts           TEXT NOT NULL,
    level        TEXT NOT NULL,             -- WARNING | ERROR | CRITICAL
    logger       TEXT NOT NULL,             -- e.g. 'yorik.email_fetcher'
    message      TEXT NOT NULL,
    traceback    TEXT,                       -- null for non-exception warnings
    request_path TEXT                        -- when emitted from inside an HTTP handler
, corr_id TEXT);

CREATE TABLE IF NOT EXISTS briefing_snapshots (
    id            BIGSERIAL PRIMARY KEY,
    template_id   TEXT NOT NULL,            -- e.g. 'day-recap'
    target_date   TEXT NOT NULL,            -- YYYY-MM-DD the briefing covers
    payload_json  TEXT NOT NULL,            -- full briefing result
    generated_at  TEXT NOT NULL,            -- when this snapshot was taken
    UNIQUE (template_id, target_date)
);

CREATE TABLE IF NOT EXISTS agent_conversations (
    id            TEXT PRIMARY KEY,
    user_role     TEXT NOT NULL,
    user_id       INTEGER,                       -- nullable for legacy rows
    messages_json TEXT NOT NULL DEFAULT '[]',    -- OpenAI-format list
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
, title TEXT, pinned INTEGER NOT NULL DEFAULT 0, ledger_json TEXT NOT NULL DEFAULT '{}', space_id INTEGER, attachment_stash TEXT NOT NULL DEFAULT '[]');

CREATE TABLE IF NOT EXISTS agent_message_traces (
    conversation_id TEXT NOT NULL,
    message_idx     INTEGER NOT NULL,
    trace_json      TEXT NOT NULL,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (conversation_id, message_idx)
);

CREATE TABLE IF NOT EXISTS contacts (
    id                  BIGSERIAL PRIMARY KEY,
    display_name        TEXT NOT NULL,
    aliases             TEXT,                          -- JSON array of strings
    kind                TEXT NOT NULL DEFAULT 'person'
                        CHECK (kind IN ('person', 'business')),
    status              TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'pending', 'spam', 'archived')),

    -- Personal fields (nullable on businesses)
    relation            TEXT,                          -- 'grandmother', 'plumber', 'employer'…
    birthday            TEXT,                          -- YYYY-MM-DD
    language_pref       TEXT,                          -- 'de' / 'en' / …
    salutation_pref     TEXT,                          -- 'du' / 'Sie' / 'first-name' / 'formal'

    -- Business fields (nullable on persons)
    legal_name          TEXT,
    tax_id              TEXT,                          -- USt-IdNr / VAT / etc.
    iban                TEXT,
    payment_terms_days  INTEGER,
    default_currency    TEXT,

    notes               TEXT,
    tags                TEXT,                          -- JSON array
    created_at          TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at          TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    created_by_user_id  INTEGER,
    last_used_at        TEXT,                          -- "I addressed a draft to them" — ranks autocomplete
    last_interaction_at TEXT,                          -- last inbound (email/WA/etc.)
    source              TEXT NOT NULL DEFAULT 'manual'
                        CHECK (source IN ('manual', 'email_in', 'wa_sync', 'paperless_ocr',
                                          'ics_import', 'vcard', 'auto'))
, address_scraped_at TEXT, pinned INTEGER NOT NULL DEFAULT 0, space_id INTEGER, first_name TEXT, last_name TEXT, role TEXT, employer_contact_id INTEGER);

CREATE TABLE IF NOT EXISTS contact_channels (
    id          BIGSERIAL PRIMARY KEY,
    contact_id  INTEGER NOT NULL,
    kind        TEXT NOT NULL
                CHECK (kind IN ('email', 'phone', 'whatsapp', 'signal',
                                'telegram', 'sms', 'website', 'social')),
    value       TEXT NOT NULL,        -- normalised: emails lower-cased, phones E.164
    label       TEXT,                  -- 'primary' / 'work' / 'home' / 'mobile' / …
    verified_at TEXT,                  -- when we last confirmed the channel works
    source      TEXT,                  -- 'manual' / 'email_in' / 'wa_sync' / …
    created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),

    -- THE killer constraint: inbound email/WA can ask
    -- "is this address known?" in one indexed hit, no JSON scan.
    UNIQUE (kind, value)
);

CREATE TABLE IF NOT EXISTS contact_addresses (
    id          BIGSERIAL PRIMARY KEY,
    contact_id  INTEGER NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'home'
                CHECK (kind IN ('home', 'work', 'billing', 'shipping', 'other')),
    line1       TEXT,
    line2       TEXT,
    postcode    TEXT,
    city        TEXT,
    region      TEXT,                  -- state / canton / Bundesland
    country     TEXT,                  -- ISO 3166-1 alpha-2 ideally
    label       TEXT,
    source      TEXT,
    created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS contact_address_suggestions (
    id              BIGSERIAL PRIMARY KEY,
    contact_id      INTEGER NOT NULL,
    -- Source channel the candidate came from ('email' / 'whatsapp').
    source_kind     TEXT NOT NULL,
    -- A short pointer into source — message id or thread id — so the
    -- user can verify "where did Yorik find this?" later if needed.
    source_ref      TEXT,
    line1           TEXT,
    line2           TEXT,
    postcode        TEXT,
    city            TEXT,
    region          TEXT,
    country         TEXT,
    -- LLM confidence 0-1 (or null if heuristic-only).
    confidence      DOUBLE PRECISION,
    -- The original passage the address was extracted from, kept so
    -- the UI can show "found in: 'we live at Hauptstr. 5, Berlin'".
    excerpt         TEXT,
    scraped_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS calendars (
    id              BIGSERIAL PRIMARY KEY,
    name            TEXT NOT NULL,
    -- Hex like '#a78bfa'. UI uses this for the chip color and the
    -- sidebar eye-toggle dot.
    color           TEXT NOT NULL DEFAULT '#a78bfa',
    owner_user_id   INTEGER NOT NULL,
    -- 'personal'  → auto-created on user signup, owned by that user
    -- 'shared'    → household / business default, write-shared with all
    -- 'project'   → user-created arbitrary calendar
    kind            TEXT NOT NULL DEFAULT 'personal',
    -- When 1, even admin role cannot read events on this calendar
    -- unless explicitly shared. Off by default — admin sees all so the
    -- household head / business owner has the full picture.
    hide_from_admin INTEGER NOT NULL DEFAULT 0,
    -- Soft delete so historical events don't break.
    archived_at     TEXT,
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), space_id INTEGER
);

CREATE TABLE IF NOT EXISTS event_attendees (
    id                  BIGSERIAL PRIMARY KEY,
    event_id            INTEGER NOT NULL,
    user_id             INTEGER,          -- nullable when person_name is set
    person_name         TEXT,             -- nullable when user_id is set
    -- 'needs_action' default until the user RSVPs.
    -- 'accepted' / 'declined' / 'tentative' are the three responses.
    -- Non-user attendees (person_name) stay 'needs_action' forever — UI
    -- treats them as informational.
    response_status     TEXT NOT NULL DEFAULT 'needs_action',
    -- Counter-proposal time the attendee suggested instead of the
    -- event's start. Single counter, no thread — keeps the flow simple.
    proposed_time_iso   TEXT,
    response_at         TEXT,
    created_at          TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    -- Guard: exactly one of (user_id, person_name) must be set.
    CHECK ((user_id IS NULL) <> (person_name IS NULL))
);

CREATE TABLE IF NOT EXISTS web_visits (
    id        BIGSERIAL PRIMARY KEY,
    user_id   INTEGER NOT NULL,
    action    TEXT NOT NULL,
    query     TEXT,
    url       TEXT,
    provider  TEXT,
    ok        INTEGER NOT NULL DEFAULT 1,
    status    INTEGER,
    bytes     INTEGER,
    error     TEXT,
    at        TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS email_blocklist (
    id              BIGSERIAL PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    sender_address  TEXT,                       -- lowercase, full address
    sender_domain   TEXT,                       -- lowercase, no leading '@'
    reason          TEXT,                       -- free-form, optional
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    -- Exactly one of the two address columns must be set.
    CHECK ((sender_address IS NOT NULL) <> (sender_domain IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS "wa_messages" (
            msg_id             TEXT NOT NULL,
            chat_jid           TEXT NOT NULL,
            from_me            INTEGER NOT NULL DEFAULT 0,
            participant        TEXT,
            push_name          TEXT,
            timestamp          INTEGER NOT NULL,
            text               TEXT,
            media_kind         TEXT,
            mimetype           TEXT,
            filename           TEXT,
            media_local_path   TEXT,
            media_paperless_id INTEGER,
            media_immich_id    TEXT,
            transcript         TEXT,
            owner_user_id      INTEGER NOT NULL DEFAULT 1,
            created_at         TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), space_id INTEGER,
            PRIMARY KEY (chat_jid, msg_id, owner_user_id)
        );

CREATE TABLE IF NOT EXISTS household_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_by_user_id INTEGER
);

CREATE TABLE IF NOT EXISTS contact_enrichment_proposals (
    id              BIGSERIAL PRIMARY KEY,
    contact_id      INTEGER NOT NULL,
    field_name      TEXT NOT NULL,
    proposed_value  TEXT NOT NULL,
    confidence      DOUBLE PRECISION NOT NULL DEFAULT 0.5,   -- 0.0..1.0
    source_kind     TEXT NOT NULL,
    source_ref      TEXT,                        -- e.g. paperless doc id, email msg id
    source_snippet  TEXT,                        -- short text the LLM extracted this from
    status          TEXT NOT NULL DEFAULT 'pending',  -- pending | accepted | rejected
    created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    decided_at      TEXT
);

CREATE TABLE IF NOT EXISTS compose_draft_versions (
    id            BIGSERIAL PRIMARY KEY,
    draft_id      INTEGER NOT NULL,
    body_html     TEXT NOT NULL,
    source        TEXT NOT NULL,                   -- initial | refine | manual | restore
    instruction   TEXT,                            -- refine: the user's instruction text
    restored_from INTEGER,  -- restore: the version we swapped to
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS workspaces (
            id            BIGSERIAL PRIMARY KEY,
            name          TEXT NOT NULL,
            kind          TEXT NOT NULL CHECK (kind IN ('family', 'business')),
            owner_user_id INTEGER NOT NULL,
            created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
        );

CREATE TABLE IF NOT EXISTS spaces (
            id             BIGSERIAL PRIMARY KEY,
            workspace_id   INTEGER NOT NULL,
            name           TEXT NOT NULL,
            kind           TEXT NOT NULL CHECK (kind IN ('personal', 'shared')),
            owner_user_id  INTEGER,
            slug           TEXT,
            color          TEXT,
            icon           TEXT,
            created_at     TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE (workspace_id, slug)
        );

CREATE TABLE IF NOT EXISTS space_members (
            space_id          INTEGER NOT NULL,
            user_id           INTEGER NOT NULL,
            level             TEXT NOT NULL CHECK (level IN ('read', 'write', 'admin')),
            added_at          TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
            added_by_user_id  INTEGER,
            PRIMARY KEY (space_id, user_id)
        );

CREATE TABLE IF NOT EXISTS row_shares (
            id                BIGSERIAL PRIMARY KEY,
            table_name        TEXT NOT NULL,
            row_id            INTEGER NOT NULL,
            user_id           INTEGER NOT NULL,
            level             TEXT NOT NULL CHECK (level IN ('read', 'write')),
            shared_by_user_id INTEGER,
            shared_at         TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE (table_name, row_id, user_id)
        );

CREATE TABLE IF NOT EXISTS pending_actions (
                id              TEXT PRIMARY KEY,
                user_id         INTEGER NOT NULL,
                skill           TEXT NOT NULL,
                params_json     TEXT NOT NULL,
                preview_json    TEXT NOT NULL,
                rollback_kind   TEXT NOT NULL DEFAULT '',
                rollback_args_json TEXT NOT NULL DEFAULT '{}',
                llm_model       TEXT NOT NULL DEFAULT '',
                language        TEXT NOT NULL DEFAULT 'en',
                created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
            );

CREATE TABLE IF NOT EXISTS skill_decisions (
                id              BIGSERIAL PRIMARY KEY,
                skill           TEXT NOT NULL,
                llm_model       TEXT NOT NULL DEFAULT '',
                language        TEXT NOT NULL DEFAULT 'en',
                decision        TEXT NOT NULL CHECK (decision IN ('confirmed','cancelled','test','auto')),
                user_id         INTEGER NOT NULL,
                params_json     TEXT NOT NULL DEFAULT '{}',
                ts              TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
            );

CREATE TABLE IF NOT EXISTS contact_extraction_proposals (
    id                      BIGSERIAL PRIMARY KEY,
    source_paperless_doc_id INTEGER NOT NULL,
    -- Snapshot of what the extractor produced; immutable once written.
    -- Schema: {display_name, kind, business_name?, legal_name?,
    --          address_street?, address_postcode?, address_city?,
    --          address_country?, email?, phone?, iban?, tax_id?,
    --          salutation_pref?, source_snippet?}
    proposed_json           TEXT NOT NULL,
    -- Match against existing contacts. NULL = looks new.
    match_candidate_id      INTEGER,
    match_score             DOUBLE PRECISION,                       -- 0..1 from the matcher
    match_reason            TEXT,                       -- "iban", "name+city", "name", …
    status                  TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'accepted', 'rejected', 'merged', 'skipped')),
    -- Set when admin accepts/merges. NULL for pending/rejected.
    created_contact_id      INTEGER,
    created_at              TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    decided_at              TEXT,
    decided_by_user_id      INTEGER,
    UNIQUE (source_paperless_doc_id)
);

CREATE TABLE IF NOT EXISTS email_deleted_message_ids (
    account_id  INTEGER NOT NULL,
    message_id  TEXT    NOT NULL,
    deleted_at  TEXT    NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), suppress_folder_id INTEGER DEFAULT NULL,
    PRIMARY KEY (account_id, message_id)
);

CREATE TABLE IF NOT EXISTS trusted_kiosk_devices (
    device_id              TEXT PRIMARY KEY,    -- UUID from the wrapper
    user_id                INTEGER NOT NULL,    -- admin who trusted it
    device_label           TEXT,                -- "Living Room Tablet" etc.
    kiosk_album_id         TEXT,
    kiosk_show_today       INTEGER NOT NULL DEFAULT 0,
    kiosk_hotword_enabled  INTEGER NOT NULL DEFAULT 0,
    kiosk_block_phrases    TEXT,                -- JSON array
    created_at             TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at           TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =================== documents.db tables (docs schema) ===================

CREATE TABLE IF NOT EXISTS docs.documents (
    id            BIGSERIAL PRIMARY KEY,
    title         TEXT NOT NULL,
    path          TEXT NOT NULL,
    mime_type     TEXT,
    bytes         INTEGER,
    tags          TEXT,
    allowed_roles TEXT NOT NULL DEFAULT 'admin',
    chunk_count   INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    indexed_at    TEXT
, owner_user_id INTEGER NOT NULL DEFAULT 1);

CREATE TABLE IF NOT EXISTS docs.document_chunks (
    id          BIGSERIAL PRIMARY KEY,
    doc_id      INTEGER NOT NULL,
    chunk_index INTEGER NOT NULL,
    text        TEXT NOT NULL,
    char_start  INTEGER,
    char_end    INTEGER,
    embedded_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS docs.paperless_chunks (
    id               BIGSERIAL PRIMARY KEY,
    paperless_doc_id INTEGER NOT NULL,
    chunk_index      INTEGER NOT NULL,
    text             TEXT NOT NULL,
    char_start       INTEGER,
    char_end         INTEGER,
    ingested_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), space_id INTEGER,
    UNIQUE(paperless_doc_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS docs.wa_chunks (
                id            BIGSERIAL PRIMARY KEY,
                chat_jid      TEXT NOT NULL,
                msg_id        TEXT NOT NULL,
                text          TEXT NOT NULL,
                timestamp     INTEGER NOT NULL,
                push_name     TEXT,
                from_me       INTEGER NOT NULL DEFAULT 0,
                UNIQUE (chat_jid, msg_id)
            );

-- =================== indexes (family.db) ===================

CREATE INDEX IF NOT EXISTS ix_sessions_user_expires ON sessions(user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS ix_wa_chats_last_ts ON wa_chats(last_message_ts DESC);
CREATE INDEX IF NOT EXISTS ix_wa_drafts_chat ON wa_drafts(chat_jid, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_email_accounts_owner ON email_accounts(owner_user_id, enabled DESC);
CREATE INDEX IF NOT EXISTS ix_email_msgs_owner_date ON email_messages(owner_user_id, date_received DESC);
CREATE INDEX IF NOT EXISTS ix_email_msgs_thread     ON email_messages(thread_id);
CREATE INDEX IF NOT EXISTS ix_email_msgs_unread     ON email_messages(owner_user_id, is_unread, date_received DESC);
CREATE INDEX IF NOT EXISTS ix_email_drafts_msg     ON email_drafts(message_id, status);
CREATE INDEX IF NOT EXISTS ix_email_drafts_pending ON email_drafts(owner_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_backups_started ON backups(started_at DESC);
CREATE INDEX IF NOT EXISTS ix_task_assignees_user ON task_assignees(user_id, status);
CREATE INDEX IF NOT EXISTS ix_notifications_user_unread
    ON notifications(user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_document_series_kind ON document_series(kind, is_default);
CREATE INDEX IF NOT EXISTS ix_document_series_alloc_series_consumed
    ON document_series_allocations(series_id, consumed_at DESC);
CREATE INDEX IF NOT EXISTS ix_turn_feedback_model_created
    ON turn_feedback(llm_model, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_skill_invocations_skill_model
    ON skill_invocations(skill_id, llm_model, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_template_ratings_template
    ON template_ratings(template_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_compose_drafts_user
                ON compose_drafts (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_error_log_ts_desc ON error_log (ts DESC);
CREATE INDEX IF NOT EXISTS ix_error_log_level   ON error_log (level);
CREATE INDEX IF NOT EXISTS ix_briefing_snapshots_date_desc
    ON briefing_snapshots (target_date DESC);
CREATE INDEX IF NOT EXISTS ix_agent_conversations_updated
    ON agent_conversations (updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_agent_conversations_user
    ON agent_conversations (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_agent_message_traces_conv
    ON agent_message_traces (conversation_id);
CREATE INDEX IF NOT EXISTS ix_contacts_status_used
    ON contacts (status, last_used_at DESC);
CREATE INDEX IF NOT EXISTS ix_contacts_kind
    ON contacts (kind, status);
CREATE INDEX IF NOT EXISTS ix_contact_channels_contact
    ON contact_channels (contact_id);
CREATE INDEX IF NOT EXISTS ix_contact_addresses_contact
    ON contact_addresses (contact_id);
CREATE INDEX IF NOT EXISTS ix_contact_addr_sugg_contact
    ON contact_address_suggestions(contact_id, scraped_at DESC);
CREATE INDEX IF NOT EXISTS ix_calendars_owner ON calendars(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_events_calendar ON events(calendar_id);
CREATE INDEX IF NOT EXISTS ix_events_owner    ON events(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_event_attendees_event ON event_attendees(event_id);
CREATE INDEX IF NOT EXISTS ix_event_attendees_user  ON event_attendees(user_id);
CREATE INDEX IF NOT EXISTS ix_tasks_created_by ON tasks(created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_web_visits_user_at
    ON web_visits(user_id, at DESC);
CREATE INDEX IF NOT EXISTS ix_agent_conversations_pinned
    ON agent_conversations (pinned DESC, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_tasks_parent
    ON tasks (parent_task_id);
CREATE INDEX IF NOT EXISTS ix_email_msgs_snoozed
    ON email_messages (owner_user_id, snoozed_until);
CREATE INDEX IF NOT EXISTS ix_contacts_pinned
    ON contacts (pinned DESC, status);
CREATE INDEX IF NOT EXISTS ix_email_blocklist_user_address
    ON email_blocklist (user_id, sender_address);
CREATE INDEX IF NOT EXISTS ix_email_blocklist_user_domain
    ON email_blocklist (user_id, sender_domain);
CREATE UNIQUE INDEX IF NOT EXISTS ux_email_blocklist_user_address
    ON email_blocklist (user_id, sender_address)
 WHERE sender_address IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_email_blocklist_user_domain
    ON email_blocklist (user_id, sender_domain)
 WHERE sender_domain IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_wa_messages_chat_ts
            ON wa_messages(chat_jid, timestamp DESC);
CREATE INDEX IF NOT EXISTS ix_wa_messages_ts
            ON wa_messages(timestamp DESC);
CREATE INDEX IF NOT EXISTS ix_cep_contact     ON contact_enrichment_proposals(contact_id);
CREATE INDEX IF NOT EXISTS ix_cep_contact_fld ON contact_enrichment_proposals(contact_id, field_name);
CREATE INDEX IF NOT EXISTS ix_cep_pending     ON contact_enrichment_proposals(status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS ix_cdv_draft ON compose_draft_versions(draft_id, id);
CREATE INDEX IF NOT EXISTS idx_row_shares_row ON row_shares (table_name, row_id);
CREATE INDEX IF NOT EXISTS idx_row_shares_user ON row_shares (user_id);
CREATE INDEX IF NOT EXISTS idx_space_members_user ON space_members (user_id);
CREATE INDEX IF NOT EXISTS ix_pending_actions_user
                ON pending_actions (user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_skill_decisions_skill_model
                ON skill_decisions (skill, llm_model, decision);
CREATE INDEX IF NOT EXISTS ix_skill_decisions_ts
                ON skill_decisions (ts);
CREATE INDEX IF NOT EXISTS ix_cxp_status   ON contact_extraction_proposals(status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS ix_cxp_match    ON contact_extraction_proposals(match_candidate_id);
CREATE INDEX IF NOT EXISTS ix_cxp_created  ON contact_extraction_proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_deleted_msgid
    ON email_deleted_message_ids (message_id);
CREATE INDEX IF NOT EXISTS idx_contacts_employer
    ON contacts(employer_contact_id)
    WHERE employer_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_sessions_kiosk
    ON sessions(is_kiosk)
    WHERE is_kiosk = 1;
CREATE INDEX IF NOT EXISTS ix_trusted_kiosk_devices_user ON trusted_kiosk_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_events_space_id ON events (space_id);
CREATE INDEX IF NOT EXISTS idx_connector_credentials_workspace_id ON connector_credentials (workspace_id);
CREATE INDEX IF NOT EXISTS idx_connector_grants_workspace_id ON connector_grants (workspace_id);
CREATE INDEX IF NOT EXISTS idx_conversations_space_id ON conversations (space_id);
CREATE INDEX IF NOT EXISTS idx_email_accounts_space_id ON email_accounts (space_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_space_id ON email_messages (space_id);
CREATE INDEX IF NOT EXISTS idx_email_drafts_space_id ON email_drafts (space_id);
CREATE INDEX IF NOT EXISTS idx_email_folders_space_id ON email_folders (space_id);
CREATE INDEX IF NOT EXISTS idx_email_attachments_space_id ON email_attachments (space_id);
CREATE INDEX IF NOT EXISTS idx_wa_chats_space_id ON wa_chats (space_id);
CREATE INDEX IF NOT EXISTS idx_wa_messages_space_id ON wa_messages (space_id);
CREATE INDEX IF NOT EXISTS idx_wa_drafts_space_id ON wa_drafts (space_id);
CREATE INDEX IF NOT EXISTS idx_wa_self_identity_space_id ON wa_self_identity (space_id);
CREATE INDEX IF NOT EXISTS idx_notifications_space_id ON notifications (space_id);
CREATE INDEX IF NOT EXISTS idx_saved_queries_workspace_id ON saved_queries (workspace_id);
CREATE INDEX IF NOT EXISTS idx_document_series_workspace_id ON document_series (workspace_id);
CREATE INDEX IF NOT EXISTS idx_document_series_allocations_workspace_id ON document_series_allocations (workspace_id);

-- =================== indexes (documents.db, docs schema) ===================

CREATE INDEX IF NOT EXISTS idx_document_chunks_doc_id ON docs.document_chunks(doc_id);
CREATE INDEX IF NOT EXISTS idx_paperless_chunks_doc ON docs.paperless_chunks(paperless_doc_id);
CREATE INDEX IF NOT EXISTS ix_wa_chunks_chat ON docs.wa_chunks(chat_jid, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_paperless_chunks_space_id ON docs.paperless_chunks (space_id);

-- =================== Embeddings (pgvector replaces sqlite_vec) ===================

-- paperless_vec (sqlite_vec virtual) → docs.paperless_chunks.embedding vector(384)
ALTER TABLE docs.paperless_chunks ADD COLUMN IF NOT EXISTS embedding vector(384);
CREATE INDEX IF NOT EXISTS idx_paperless_chunks_embedding ON docs.paperless_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- wa_vec (sqlite_vec virtual) → wa_messages.embedding vector(384)
ALTER TABLE wa_messages ADD COLUMN IF NOT EXISTS embedding vector(384);
CREATE INDEX IF NOT EXISTS idx_wa_messages_embedding ON wa_messages USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- vec_chunks (sqlite_vec virtual) → docs.document_chunks.embedding vector(384)
ALTER TABLE docs.document_chunks ADD COLUMN IF NOT EXISTS embedding vector(384);
CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON docs.document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- =================== Full-text search (tsvector replaces FTS5) ===================

-- email_messages_fts (FTS5) → email_messages.search_tsv tsvector (generated)
ALTER TABLE email_messages ADD COLUMN IF NOT EXISTS search_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(subject, '') || ' ' || coalesce(from_name, '') || ' ' || coalesce(from_email, '') || ' ' || coalesce(snippet, '') || ' ' || coalesce(body_text, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_email_messages_search_tsv ON email_messages USING gin (search_tsv);

-- wa_messages_fts (FTS5) → wa_messages.search_tsv tsvector (generated)
ALTER TABLE wa_messages ADD COLUMN IF NOT EXISTS search_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(text, '') || ' ' || coalesce(transcript, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_wa_messages_search_tsv ON wa_messages USING gin (search_tsv);

-- =================== schema_migrations stamp ===================
CREATE TABLE IF NOT EXISTS schema_migrations (
    version    INTEGER PRIMARY KEY,
    name       TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp
);
-- Stamping version 0 (phase_d_init) + 62 historical migrations as applied.
INSERT INTO schema_migrations (version, name) VALUES (0, 'phase_d_init') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (1, 'encrypt_per_user_external_tokens') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (2, 'error_log_table') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (3, 'briefing_snapshots') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (4, 'email_imap_starttls') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (5, 'agent_conversations') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (6, 'user_dev_mode') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (7, 'agent_message_traces') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (8, 'contacts') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (9, 'contact_address_scrape_cache') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (10, 'calendars_and_attendees') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (11, 'rename_shared_to_household') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (12, 'tasks_creator_and_revert_name') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (13, 'doc_default_visibility') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (14, 'wa_channels_full_jid_cleanup') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (15, 'wa_contacts_active_by_default') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (16, 'wa_channels_restore_jid_suffix') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (17, 'user_first_last_name') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (18, 'user_signature') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (19, 'events_location_and_travel') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (20, 'web_visits_audit') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (21, 'agent_conversation_title') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (22, 'agent_conversation_pin') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (23, 'tasks_subtask_recurrence') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (24, 'email_snooze') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (25, 'contacts_pinned') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (26, 'events_category') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (27, 'email_blocklist') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (28, 'email_list_unsubscribe') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (29, 'wa_messages_pk_owner') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (30, 'calendar_colors_distinct') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (31, 'contact_shares_and_household_settings') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (32, 'documents_default_visibility') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (33, 'contact_enrichment_proposals') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (34, 'compose_draft_versions') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (35, 'agent_conversation_ledger') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (36, 'phase_b_spaces') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (37, 'drop_allowed_roles') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (38, 'backfill_is_sent_from_folder_flags') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (39, 'truncate_task_bill_due_dates') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (40, 'contact_extraction_proposals') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (41, 'agent_conversation_attachment_stash') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (42, 'purge_nameless_lid_pending_contacts') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (43, 'email_deleted_message_ids') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (44, 'email_tombstone_folder_scope') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (45, 'contact_persons') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (46, 'contact_persons_backfill') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (47, 'user_pin_hash') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (48, 'sessions_kiosk') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (49, 'sessions_kiosk_today') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (50, 'sessions_kiosk_block_phrases') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (51, 'sessions_kiosk_hotword') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (52, 'trusted_kiosk_devices') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (53, 'rename_household_space_to_shared') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (54, 'user_kiosk_agenda_consent') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (55, 'paperless_chunks_space_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (56, 'events_space_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (57, 'connector_workspace_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (58, 'conversations_space_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (59, 'email_space_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (60, 'wa_space_id') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (61, 'remaining_tables_scoping') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version, name) VALUES (62, 'platform_admin_role') ON CONFLICT (version) DO NOTHING;
