#!/usr/bin/env bash
# scripts/immich-ml-backend.sh — switch the bundled Immich ML container
# between CPU and the various Immich GPU acceleration backends without
# editing config.env or docker-compose.yml by hand.
#
# Mechanism:
#   1. Persist the choice to config.env (YORIK_IMMICH_GPU=...).
#   2. Generate / refresh a per-backend override file
#      (docker-compose.<backend>.yml) — installed alongside the existing
#      docker-compose.nvidia.yml so start.sh picks it up next boot.
#   3. Run preflight checks (driver, kernel device, container toolkit).
#   4. Recreate just the immich-machine-learning container.
#   5. Tail its logs briefly and grep for the "Available ORT providers"
#      / "Loaded ANN model" marker that confirms the device is live.
#
# Usage:
#   bash scripts/immich-ml-backend.sh status
#   bash scripts/immich-ml-backend.sh set cpu
#   bash scripts/immich-ml-backend.sh set nvidia    # CUDA / NVIDIA
#   bash scripts/immich-ml-backend.sh set openvino  # Intel iGPU / Arc
#   bash scripts/immich-ml-backend.sh set rocm      # AMD
#   bash scripts/immich-ml-backend.sh set armnn     # Mali ARM
#   bash scripts/immich-ml-backend.sh set rknn      # Rockchip NPU
#
# Safe to run repeatedly — `set` is idempotent. To revert to CPU, just
# `set cpu`; the override file gets removed and the standard CPU image
# is used on next start.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

CONFIG="$ROOT/config.env"

err() { echo "✗ $*" >&2; exit 1; }
ok()  { echo "✓ $*"; }
info(){ echo "  $*"; }

# ── Backend → Immich image tag map ───────────────────────────────────

backend_image_tag() {
  case "$1" in
    cpu)      echo "release" ;;
    nvidia)   echo "release-cuda" ;;
    openvino) echo "release-openvino" ;;
    rocm)     echo "release-rocm" ;;
    armnn)    echo "release-armnn" ;;
    rknn)     echo "release-rknn" ;;
    *)        err "unknown backend: $1 (cpu | nvidia | openvino | rocm | armnn | rknn)" ;;
  esac
}

# ── Override-file generation per backend ─────────────────────────────
#
# These mirror Immich's hwaccel.ml.yml service definitions but inline
# the relevant section into a Yorik-shaped service block (matching the
# bundled docker-compose.yml's container_name / volumes / profile).

generate_override() {
  local backend="$1"
  local out="$ROOT/docker-compose.${backend}.yml"
  case "$backend" in
    cpu)
      # No override file for CPU — remove any leftover.
      rm -f "$out"
      ok "removed $out (CPU uses no override)"
      return 0
      ;;
    nvidia)
      # Don't clobber the hand-maintained NVIDIA override that ships
      # with the repo. Only generate it if missing.
      if [[ -f "$out" ]]; then
        info "keeping existing $out"
        return 0
      fi
      cat >"$out" <<'YAML'
# Immich GPU passthrough for NVIDIA hosts (generated by
# scripts/immich-ml-backend.sh). Requires nvidia-container-toolkit.
services:
  immich-server:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
YAML
      ;;
    openvino)
      cat >"$out" <<'YAML'
# Intel iGPU / Arc — OpenVINO. /dev/dri must be exposed (Intel media
# driver on the host). Higher RAM usage than CPU.
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    devices:
      - /dev/dri:/dev/dri
YAML
      ;;
    rocm)
      cat >"$out" <<'YAML'
# AMD GPU — ROCm. Image is ~35 GiB; first pull is slow. /dev/kfd is
# the ROCm kernel-fusion driver, /dev/dri is the render node.
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-rocm
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
YAML
      ;;
    armnn)
      cat >"$out" <<'YAML'
# ARM Mali GPU (Rockchip / Allwinner SoCs). Requires the closed-source
# libmali.so firmware on the host — vendor-supplied, path may differ.
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-armnn
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /usr/lib/libmali.so:/usr/lib/libmali.so:ro
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro
YAML
      ;;
    rknn)
      cat >"$out" <<'YAML'
# Rockchip NPU (RK3566 / RK3568 / RK3576 / RK3588). Adjust
# MACHINE_LEARNING_RKNN_THREADS in config.env to 2-3 on RK3576/RK3588
# for substantially higher throughput (at proportionally more RAM).
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-rknn
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
YAML
      ;;
  esac
  ok "wrote $out"
}

# ── Preflight per backend ────────────────────────────────────────────

preflight() {
  local backend="$1"
  case "$backend" in
    cpu)
      ok "cpu: no prerequisites"
      ;;
    nvidia)
      command -v nvidia-smi >/dev/null \
        || err "nvidia-smi not found — install the NVIDIA driver (>= 545) first"
      nvidia-smi >/dev/null 2>&1 \
        || err "nvidia-smi failed — driver not loaded? Check 'sudo dmesg | tail'"
      ok "nvidia-smi works: $(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"
      if ! docker info 2>/dev/null | grep -qE "Runtimes:.*\bnvidia\b"; then
        err "Docker doesn't see the NVIDIA runtime. Install nvidia-container-toolkit:
  sudo apt install -y nvidia-container-toolkit
  sudo systemctl restart docker"
      fi
      ok "Docker nvidia runtime registered"
      ;;
    openvino)
      [[ -d /dev/dri ]] || err "/dev/dri missing — Intel media driver not present?"
      ok "/dev/dri present"
      info "(expect 5-15% higher RAM use than CPU)"
      ;;
    rocm)
      [[ -d /dev/dri ]] || err "/dev/dri missing — ROCm driver not loaded?"
      [[ -e /dev/kfd ]] || err "/dev/kfd missing — kfd kernel module not loaded (modprobe amdgpu)"
      ok "/dev/dri + /dev/kfd present"
      info "(image is ~35 GiB on first pull; subsequent updates are cached)"
      ;;
    armnn)
      [[ -e /dev/mali0 ]] \
        || err "/dev/mali0 missing — Mali kernel driver not loaded on this host"
      [[ -f /usr/lib/libmali.so ]] \
        || err "/usr/lib/libmali.so missing — install the closed-source Mali firmware (vendor-supplied)"
      ok "Mali driver + firmware present"
      ;;
    rknn)
      [[ -f /sys/kernel/debug/rknpu/version ]] \
        || err "RKNPU driver missing or /sys/kernel/debug not mounted — supported only on RK3566/68/76/88"
      ok "RKNPU driver: $(cat /sys/kernel/debug/rknpu/version 2>/dev/null || echo 'unknown')"
      ;;
  esac
}

# ── config.env persistence ───────────────────────────────────────────

set_config() {
  local backend="$1"
  touch "$CONFIG"
  if grep -q "^YORIK_IMMICH_GPU=" "$CONFIG"; then
    # In-place edit, BSD/GNU sed compatible
    if sed --version >/dev/null 2>&1; then
      sed -i "s|^YORIK_IMMICH_GPU=.*|YORIK_IMMICH_GPU=$backend|" "$CONFIG"
    else
      sed -i '' "s|^YORIK_IMMICH_GPU=.*|YORIK_IMMICH_GPU=$backend|" "$CONFIG"
    fi
  else
    echo "YORIK_IMMICH_GPU=$backend" >> "$CONFIG"
  fi
  ok "config.env: YORIK_IMMICH_GPU=$backend"
}

# ── Subcommands ──────────────────────────────────────────────────────

cmd_status() {
  echo "Current Immich ML configuration:"
  if [[ -f "$CONFIG" ]] && grep -q "^YORIK_IMMICH_GPU=" "$CONFIG"; then
    local cur
    cur=$(grep "^YORIK_IMMICH_GPU=" "$CONFIG" | tail -1 | cut -d= -f2)
    info "config.env: YORIK_IMMICH_GPU=$cur"
  else
    info "config.env: YORIK_IMMICH_GPU not set (defaults to cpu)"
  fi
  echo
  echo "Override files present:"
  for f in "$ROOT"/docker-compose.{nvidia,openvino,rocm,armnn,rknn}.yml; do
    [[ -f "$f" ]] && info "  $f"
  done
  echo
  echo "Container state:"
  if docker ps --format '{{.Names}}|{{.Image}}|{{.Status}}' 2>/dev/null \
       | grep '^yorik-immich-ml|'; then
    docker ps --format '  {{.Names}}  {{.Image}}  ({{.Status}})' | grep yorik-immich-ml
  else
    info "yorik-immich-ml is NOT running"
  fi
}

cmd_set() {
  local backend="${1:-}"
  [[ -n "$backend" ]] || err "usage: $0 set <cpu | nvidia | openvino | rocm | armnn | rknn>"
  # Validate backend name early
  backend_image_tag "$backend" >/dev/null
  echo "→ switching immich-ml backend to: $backend"
  echo
  preflight "$backend"
  echo
  generate_override "$backend"
  set_config "$backend"
  echo
  echo "→ recreating immich-machine-learning container…"
  local extra=()
  if [[ "$backend" != "cpu" ]]; then
    extra=("-f" "docker-compose.${backend}.yml")
  fi
  # --no-deps so we don't restart immich-server / postgres / redis,
  # only the ML service. --force-recreate so the new image tag is
  # picked up even when no compose-level setting changed.
  docker compose -f docker-compose.yml "${extra[@]}" --profile bundled-immich \
    up -d --no-deps --force-recreate immich-machine-learning
  echo
  ok "container recreated"
  echo
  echo "→ tailing immich-ml logs for ~15s to confirm device activation…"
  echo "  (look for 'Available ORT providers' / 'Loaded ANN model')"
  echo
  # Don't fail the script if grep finds nothing — the user can re-check
  # with `docker logs yorik-immich-ml | grep providers`.
  ( timeout 15 docker logs -f yorik-immich-ml 2>&1 \
      | grep --line-buffered -iE "Available ORT|Loaded ANN|using device|cuda|openvino|rocm|rknn|armnn|error" \
      || true ) | head -20
  echo
  ok "done — $backend backend is active in config.env + override file"
  echo
  echo "Monitor GPU utilization with:"
  case "$backend" in
    nvidia)  info "nvtop                        # also handles Intel" ;;
    openvino)info "intel_gpu_top                # apt install intel-gpu-tools" ;;
    rocm)    info "radeontop                    # apt install radeontop" ;;
    armnn|rknn) info "(vendor-specific tooling — check your SoC documentation)" ;;
    cpu)     info "htop                         # CPU is now bearing the load again" ;;
  esac
}

# ── Main ─────────────────────────────────────────────────────────────

case "${1:-}" in
  status)  cmd_status ;;
  set)     shift; cmd_set "$@" ;;
  *)
    cat <<EOF
Switch the bundled Immich machine-learning container between CPU and
GPU acceleration backends.

Usage:
  $0 <command>

Commands:
  status               Show current backend + container state
  set <backend>        Switch to a different backend (idempotent)

Backends:
  cpu       CPU only — works everywhere, no prerequisites
  nvidia    NVIDIA CUDA — needs driver >= 545 + nvidia-container-toolkit
  openvino  Intel iGPU / Arc — needs /dev/dri exposed
  rocm      AMD ROCm — needs /dev/dri + /dev/kfd (image is ~35 GiB)
  armnn     ARM Mali — needs /dev/mali0 + libmali.so on the host
  rknn      Rockchip NPU — needs RK3566/68/76/88 with NPU driver

Examples:
  bash $0 status
  bash $0 set nvidia
  bash $0 set cpu       # revert
EOF
    exit 1
    ;;
esac
