#!/usr/bin/env bash
# Restore Yorik from an encrypted snapshot.
#
# Usage:
#   bash scripts/restore-from-snapshot.sh <snapshot.tar.gz.age> [passphrase]
#
# Reads the passphrase from stdin if you omit the second arg (safer
# than putting it in shell history). If a `backup_passphrase` is
# stored in credential_store from a previous `set_config`, that's
# tried first as a convenience.
#
# What it does:
#   1. Verifies the snapshot decrypts + integrity-checks cleanly.
#   2. Stops yorik.service + every yorik-tenant@*.service.
#   3. Drops + recreates the host's public/yorik/docs schemas and
#      every tenant's database in the bundle's MANIFEST. Pipes each
#      pg_dump through psql.
#   4. Restores data/.credential_key, data/documents/, briefings/,
#      and each tenant's manifest.env + internal_token.
#   5. Restarts yorik.service. Each tenant systemd unit must be
#      started manually after this (see docs/RESTORE.md) so the
#      operator can confirm the tenant DB came back before exposing
#      the subdomain again.
#
# What it does NOT restore (operator's responsibility — see RESTORE.md):
#   - Immich photo library / Postgres (lives in immich container volume)
#   - Paperless data + media (lives in paperless container volumes)
#   - Caddy /etc/caddy/Caddyfile entries (regenerated by create-tenant.sh)

set -Eeuo pipefail
cd "$(dirname "$0")/.."

SNAPSHOT="${1:-}"
PASSPHRASE="${2:-}"

if [[ -z "$SNAPSHOT" ]]; then
  echo "Usage: $0 <snapshot.tar.gz.age> [passphrase]" >&2
  exit 2
fi
if [[ ! -f "$SNAPSHOT" ]]; then
  echo "snapshot not found: $SNAPSHOT" >&2
  exit 1
fi

if [[ -z "$PASSPHRASE" ]]; then
  if [[ -t 0 ]]; then
    read -r -s -p "Backup passphrase: " PASSPHRASE
    echo
  else
    read -r PASSPHRASE
  fi
fi

if [[ -z "$PASSPHRASE" ]]; then
  echo "no passphrase supplied" >&2
  exit 1
fi

echo "▸ stopping yorik + every tenant unit"
if systemctl list-units --type=service --all 2>/dev/null | grep -qE 'yorik-tenant@[a-z0-9_]+\.service'; then
  for u in $(systemctl list-units --type=service --all --no-legend 2>/dev/null \
             | awk '{print $1}' | grep -E '^yorik-tenant@[a-z0-9_]+\.service'); do
    systemctl stop "$u" 2>/dev/null || true
  done
fi
sudo systemctl stop yorik 2>/dev/null || true
# Belt + braces: kill any rogue uvicorn that survived (e.g. ad-hoc launches).
pkill -f "uvicorn backend.main:app" 2>/dev/null || true
sleep 2

echo "▸ running restore"
if [[ -d venv ]]; then source venv/bin/activate; fi
export PYTHONPATH=.

python3 -c "
import json
from pathlib import Path
from backend.backup import restore_snapshot
r = restore_snapshot(Path('$SNAPSHOT'), '''${PASSPHRASE//\'/\\\'}''')
print(json.dumps({k: v for k, v in r.items() if k != 'verify'}, indent=2, default=str))
print()
print('verify:', r['verify']['summary'])
print('summary:', r['summary'])
import sys
sys.exit(0 if r['ok'] else 1)
"
RESTORE_RC=$?

echo
echo "▸ restarting yorik"
sudo systemctl start yorik

echo
if [[ "$RESTORE_RC" == "0" ]]; then
  echo "✓ restore complete"
  echo "  Next: start each tenant: sudo systemctl start yorik-tenant@<name>"
  echo "  Then: sudo systemctl reload caddy (only if Caddyfile snippets were missing)"
else
  echo "✗ restore reported errors — see steps above"
  exit "$RESTORE_RC"
fi
